'use strict';
{
  const btn=document.getElementById('btn');

  btn.addEventListener('click',()=>{
    const results=['FISH','EGG','BEEF','TOAST','VEGETABLE','NATTO','CURRY','CHICKEN','PORK','TOMATO','CHEESE','CHOCOLATE','BEER','ICE CREAM','YAKISOBA','OKONOMIYAKI','NOODLE','HAMBURGER','SUSHI','RICE BALL','SUNDUBU','BREAD','CAKE','CREAM PUFF','CREPE','FRUITS','POTATO CHIPS','FRENCH FRIES','PICKLES','GREEN TEA','TEMPURA','APPLE PIE','MISO SOUP','TOFU','MARITOZZO','CORN SOUP','SEAFOOD','WAKAME','CANDY','PIZZA','GYOZA','SOBA','RICE','SOY MILK','NUTS','BEANS','MEAT','MOCHI','CROQUETTE','SNACK','SANDWICH','SOUP','STEW','NABE','OCTOPUS','SQUID','KEBAB','TACO','SWEETS','AVOCADO','SHRIMP','PANCAKE','MACARONI','BAOZI','PLUM','MUSHROOM','SPRING ROLL','LASAGNA','CRAB'];

    btn.textContent=results[Math.floor(Math.random()*results.length)];
  });
}
